name: Regression

on:
  push

jobs:
  Create-user:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npm run createuser    # Create User, this name is mentioned in package.json file and its file path

      # If you want to upload your HTML report on CI/CD
      - name: Upload the Cypress HTML report on GitHub Actions
        if: always()  # Your test report will still be generated if your test cases fail
        uses: actions/upload-artifact@v4
        with:
          name: Mocha Awesome HTML Report
          path: cypress/reports/html  # Giving the path of which folder needs to be uploaded

      - name: Slack Notification
        if: always()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: 'Test Automation Report https://github.com/GauravChandel/AmazonE2E/actions/${{github.run_id}}'
          SLACK_TITLE: Cypress Amazon Test Cases
          SLACK_WEBHOOK: ${{ secrets.Slack_Webhook }}  # slack_webhook is a variable which is created on git -> settings -> secrets & variables -> Actions -> new repo secret -> then any name and the URL of slack channel or slack integration
